name: SmartHarvest
version: 1.1.1
main: com.draconicvelum.SmartHarvest.SmartHarvestPlugin
api-version: 1.21
author: Draconic Velum
description: Right-click harvest with AuraSkills support

folia-supported: true

softdepend:
  - AuraSkills
  - CoreProtect

commands:
  smartharvest:
    description: SmartHarvest reload
    usage: /smartharvest reload

permissions:
  smartharvest.reload:
    description: Allows reloading SmartHarvest
    default: op
